title: Gabriela Ruiz # your name (or website title) here
logo: "https://dell-my.sharepoint.com/personal/gabriela_ruiz_dell_com/Documents/Desktop/ISR/Sales%20Academy/1638683824590.jpg?Web=1" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm persuing my BS degree in Information Technology Systems at The University of Texas Dallas.
  <br><br>
  I'm currently an Account Manager at Dell Technology/Salesworks Champion with focus on data analyst and ways to improve the tool, drive adoption, and create a more user friendly experience.  
  <br><br>
  <a href="https://www.linkedin.com/in/gabrielaruizgonzalez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
